"""Offline-first seed for the dashboard's example portfolio.

Render's disk is ephemeral (the DB starts empty on every restart) and yfinance
is frequently blocked from datacenter IPs, so the default portfolio (PETR4.SA,
VALE3.SA, HGLG11.SA) cannot rely on a live fetch to render. We ship a snapshot
of its real price history in ``seed_data/example_prices.csv`` (generated by
``scripts/gerar_seed.py``) and load it on startup whenever the Price table is
empty, using the same idempotent upsert as the sync endpoint.

Only the example portfolio is seeded; tickers the user adds still sync live via
yfinance.
"""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path

from sqlmodel import Session, select

from app.db import engine
from app.models import Price
from app.store import ensure_asset, upsert_prices

SEED_FILE = Path(__file__).parent / "seed_data" / "example_prices.csv"

_NUMERIC_FIELDS = ("open", "high", "low", "close", "adj_close", "volume")


def load_seed_rows() -> list[dict]:
    """Read the versioned seed CSV into upsert-ready payload dicts."""
    if not SEED_FILE.exists():
        return []
    rows: list[dict] = []
    with SEED_FILE.open(newline="", encoding="utf-8") as fh:
        for record in csv.DictReader(fh):
            row: dict = {
                "ticker": record["ticker"].upper(),
                "date": date.fromisoformat(record["date"]),
            }
            for field in _NUMERIC_FIELDS:
                row[field] = float(record[field])
            rows.append(row)
    return rows


def seed_if_empty() -> int:
    """Load the example portfolio from the seed file if no prices are stored yet.

    Returns the number of rows seeded (0 if the table already had data or the
    seed file is missing/empty). Idempotent thanks to the shared upsert.
    """
    with Session(engine) as session:
        if session.exec(select(Price).limit(1)).first() is not None:
            return 0
        rows = load_seed_rows()
        if not rows:
            return 0
        for ticker in sorted({r["ticker"] for r in rows}):
            ensure_asset(session, ticker)
        upsert_prices(session, rows)
        return len(rows)
